### PR TITLE
Added a bunch of python scripts

### PR DESCRIPTION
**Pull request by SVijayB**
Changes made in this pull request:
- Added Error handling.
- Added Graphs -> Matplotlib module.
- Added Random module programs.
- Added Regular expressions.

### CODE REVIEW

**Comment by DeepNinja07x** [comment]
@SVijayB......just rebase your PR. It'll be good if you create one PR per file/commit. Just do it and open PR again, I'll approve and merge it

**Comment by SVijayB** [comment]
One PR per file? Won't that be a lot?

**Comment by DeepNinja07x** [comment]
one PR per commit. Add as many files in one commit then PR

**Comment by SVijayB** [comment]
Cool, I'll do that.

**Comment by DeepNinja07x** [comment]
I'm online just send me I'll merge it asap

**Comment by SVijayB** [comment]
Yep, done. I've sent a pull request at #9 . Thanks!

**Comment by DeepNinja07x** [comment]
Merged it. You can send more

**Comment by SVijayB** [comment]
Alright! Thanks.

**Pull request closed without merging**
